### ISSUE TITLE
Detect Sky and weapon areas and use the info to modify HDR

### ISSUE THREAD

**Issue by CeeJayDK** [BlueSkyDefender/AstrayFX#1]
It occurs to me that if you're doing LDR to HDR conversions in BloomingHDR or some of your other shaders, the ability we have to now detect sky and weapon/hand models could be used to modify the amount of light coming from those areas.

The sky would be brighter than most other things, and the weapon would probably be the same brightness as most things in the scene but having the ability to adjust this could make sci-fi weapons like a pulse cannon give off a nice blue bloom.

I believe some cool things could be done with this.

**Comment by BlueSkyDefender** [comment]
![image](https://user-images.githubusercontent.com/16185319/103162062-37faa280-478f-11eb-8b09-af4c3019c09d.png)

I will be able to do this as Targeted Intensity. For Sky and weapon. update will be out soon.

**Comment by BlueSkyDefender** [comment]
Seem to be working.
