### ISSUE TITLE
Permission for automatically downloading this repository

### ISSUE THREAD

**Issue by cozyGalvinism** [BlueSkyDefender/AstrayFX#13]
Heya! I'm currently writing a ReShade installer for Linux and since you don't state an explicit license, I want to ask you whether I could add your repository to the list of automatically downloaded shaders in said installer.

Appreciate your work here!

**Comment by BlueSkyDefender** [comment]
Ya, this should be fine.  Only if they are downloaded from this repo and not re-hosted.

**Comment by cozyGalvinism** [comment]
Yup! It's basically just a regular download from this repo c:

Thank you for your time!
