### ISSUE TITLE
Temporal AA TAA not work in online game like Final Fantasy XIV FF14?

### ISSUE THREAD

**Issue by mhtvsSFrpHdE** [BlueSkyDefender/AstrayFX#3]
My game "Final Fantasy XIV" in http://reshade.me/compatibility shows it has "Good" level in DirectX 9.  
And should have depth access.

I use "Temporal AA mod" in Minecraft, it's a very powerful and high performance AA  
can remove any possible aliasing and flickering.  
Of course, reshade can't make game engine to do work like shaking camera, to make AA part to work.  
But I still hope I can get some "Temporal benefits" like to prevent flickering in motion,  
for example FXAA and SMAA can look well in static image, once I start moving,  
any small details will flickering and very annoying.  
These flickering still exist in Sparse Grid Supersampling (MSAA), but very less noticeable.

When use FXAA or SMAA, add `Temporal_AA.fx` at the bottom of one of the two shaders,  
the problem is the screen just became blur and not playable anymore,  
but no AA effect, or motion flicker reduce effect.

**Comment by liandris** [comment]
Hijacking this issue to ask a different questions about TAA...

TAA won't work at all if target game is not included in Overwatch.fxh, is this correct? Are there any tutorials to set the needed values myself or is it better to ask here to add support for a certain game? Is it okay at all? As example, the game I was interested in (Risk of Rain 2) is based on Unity engine, so I wonder if it could be possible to support most games on that engine by adding specific values once.

**Comment by mhtvsSFrpHdE** [comment]
@liandris 

I got the idea, the FFXIV is an online video game, thus Reshade standard edition detected network traffic,  
so actively denied depth and normal access. TAA fx require depth access to work.  
FFXIV is not listed in `Overwatch.fxh` but also can have TAA enabled, the key is about the depth access.

Use a modded reshade edition could avoid such limit, but also expose me to something like VAC banned.  
For example, I found https://github.com/Not-Smelly-Garbage/Reshade-Unlocked

Just enable TAA and use **default configuration** could bring temporal stabilization,  
no custom setting required.  
One youtube video tutorial about GTAV out there, he set FXAA after TAA,  
but I found that FXAA(in game) first then TAA have no problem.

You, I, we can never get true TAA without game engine's help.  
A true TAA is shaking the 3D viewport camera in high speed & minor vector to blend the multi frame image,  
thus, you get "extra viewing angle that doesn't exist in a single frame" and use them to do anti-aliasing.  
In a tradition game, the 3D viewport camera is to keep still, no extra information could be grabbed.

You can expect this TAA fx to do "one-dimension" images blend for you,  
so while you're WASD moving, those flicker edge  
which FXAA & SMAA can't do anything about it...will less noticeable.  
They still exist, but really less noticeable, which is good for me.  
TAA is cheaper than MSAA in performance consume.
