### ISSUE TITLE
RESHADE_DEPTH_INPUT preprocessor not applied.

### ISSUE THREAD

**Issue by slayermaster** [BlueSkyDefender/AstrayFX#5]
Trying with DMC4, the depth need to be resized for it to work properly. Having set the preprocessor, RadiantGI still shows wrong map size.

**Comment by BlueSkyDefender** [comment]
RESHADE_DEPTH_INPUT is not a part of RadiantGI system use the built-in one in shader.

**Comment by slayermaster** [comment]
i cant seem to find how to resize it. You have some kind of manual or documentation?

**Comment by BlueSkyDefender** [comment]
Yes in shader open up the file there should be more information.
