### ISSUE TITLE
eMotionBlur syntax error

### ISSUE THREAD

**Issue by JJ1553** [BlueSkyDefender/AstrayFX#6]
After running BOTW in CEMU with reshade it said that eMotionBlur.fx is not working so I checked the log and it gave me this 

21:42:23:148 [12380] | ERROR | Failed to load "C:\Cemu\cemu_1.22.5\reshade-shaders\Shaders\AstrayFX\eMotionBlur.fx":
C:\Cemu\cemu_1.22.5\reshade-shaders\Shaders\AstrayFX\eMotionBlur.fx(214, 8): error X3000: syntax error: unexpected 'integral literal', expected 'identifier'
C:\Cemu\cemu_1.22.5\reshade-shaders\Shaders\AstrayFX\eMotionBlur.fx(216, 37): error X3000: syntax error: unexpected '(', expected 'identifier'
C:\Cemu\cemu_1.22.5\reshade-shaders\Shaders\AstrayFX\eMotionBlur.fx(217, 1): error X3000: syntax error: unexpected '}'
C:\Cemu\cemu_1.22.5\reshade-shaders\Shaders\AstrayFX\eMotionBlur.fx(264, 19): error X3000: syntax error: unexpected '(', expected ','
C:\Cemu\cemu_1.22.5\reshade-shaders\Shaders\AstrayFX\eMotionBlur.fx(272, 61): error X3000: syntax error: unexpected '(', expected ','
C:\Cemu\cemu_1.22.5\reshade-shaders\Shaders\AstrayFX\eMotionBlur.fx(408, 14): error X3000: syntax error: unexpected '(', expected ';'

referring to the part of the code 
```
float DS(float2 texcoord)
{
  return tex2Dlod(curr_frame, float4(texcoord,0,0.125)).x;
}
```

and its references... figured I would let you know.

**Comment by BlueSkyDefender** [comment]
It has been fixed.
