### ISSUE TITLE
Best deband shader

### ISSUE THREAD

**Issue by Egor179** [BlueSkyDefender/AstrayFX#7]
Hello. Is it possible to split the Deband shader from the LimboMod into a standalone shader?
I tested various Deband shaders on the depth buffer and the shader built into LimboMod showed the best result.
Or does it only work well in this shader space?
(4K upscale video to reduce artifacts)
https://www.youtube.com/watch?v=iChZdoVo66c

**Comment by BlueSkyDefender** [comment]
Made that shader as April 1 shader. Did not think people would show interest in it. Ya it can be taken out and use else where.

**Comment by Egor179** [comment]
> Made that shader as April 1 shader. Did not think people would show interest in it. Ya it can be taken out and use else where.

Could you please do this? 1 hour digging in the code led only to a bunch of errors

**Comment by BlueSkyDefender** [comment]
One Shot folder is for shaders I don't support and people can can use the old in there for what ever they want.

I will point out the part you need.
https://github.com/BlueSkyDefender/AstrayFX/blob/fbc9b86e9cfd2d4ee658c25c1843fa2fe7de1210/Shaders/OneShot/Limbo_Mod.fx#L114-L127

**Comment by Egor179** [comment]
> One Shot folder is for shaders I don't support and people can use the code in there for what ever they want.
> 
> I will point out the part you need.
> https://github.com/BlueSkyDefender/AstrayFX/blob/fbc9b86e9cfd2d4ee658c25c1843fa2fe7de1210/Shaders/OneShot/Limbo_Mod.fx#L114-L127
> 
> also this uniform float frametime < source = "frametime"; >;

Well, after 3 hours, I only came to this view:
[https://github.com/Egor179/r/blob/main/wg.fx](url)
It looks like I was able to turn off textures and other effects from the depth buffer, but I just can't turn off the depth buffer itself.
If possible, tell me what else you need to comment out?
Or do need to completely rewrite the dither code?
